### ISSUE TITLE
Viewer Freeze on Extraction of Static Objects

### ISSUE THREAD

**Issue by ClintonButler** [DizzyThermal/TKViewer#8]
I was just testing out your great little tool and found that the client completely hung about 1300 items in or so.

**Comment by ClintonButler** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\*name*\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "tk_viewer.py", line 113, in export_sobjs
    os.path.join(export_dir, 'sobj-{0:05d}.bmp'.format(i)))
  File "C:\Users\*name*\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 1930, in save
    save_handler(self, fp, filename)
  File "C:\Users\*name*\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\BmpImagePlugin.py", line 276, in _save
    (rawmode, stride, -1))])
  File "C:\Users\*name*\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\ImageFile.py", line 509, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image

**Comment by DizzyThermal** [comment]
Thanks for the issue and trace.. Should be simple enough to fix up, I render static_objects with the client, so this was probably a porting bug.

**Comment by DizzyThermal** [comment]
@Wizbaggd give this another try. It turns out that the static objects trying to be rendered had 0 height (48 pixel width and 0 pixel height).

I check the static object height before saving now. This means that some objects may not export, but the viewer won't hang
